version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    # deploy:
    #   mode: replicated
    #   resources:
    #     limits:
    #       memory: 4G
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      # - node.name=es01
      # - cluster.name=docker-cluster
      # - discovery.seed_hosts=es02,es03
      - discovery.type=single-node
      # - ELASTIC_PASSWORD=tesis
      # - bootstrap.memory_lock=true
      # - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.http.ssl.key=certs/es01/es01.key
      # - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.transport.ssl.enabled=false
      # - xpack.security.transport.ssl.key=certs/es01/es01.key
      # - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.license.self_generated.type=basic
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    networks:
      - es-network

  cerebro:
    image: lmenezes/cerebro:0.9.4
    environment:
      - CEREBRO_PORT=9000
    networks:
      - es-network
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 9000:9000

  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  es-network:
    driver: overlay
