version: '3.8'

services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - es-network
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - node.name=elasticsearch-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node1
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - es-network
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 9200:9200
      - 9300:9300

  cerebro:
    image: lmenezes/cerebro:0.9.4
    environment:
      - CEREBRO_PORT=9000
    networks:
      - es-network
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 9000:9000

  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data

volumes:
  esdata1:
  esdata2:

networks:
  es-network:
    driver: overlay
